name: "My-SQL-DATABASE"
services:
  mysql:
    image: bitnami/mysql:9.0.1
    container_name: mysql_database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: 'mysql_root'
      MYSQL_ROOT_PASSWORD: '1234567890'
      MYSQL_DATABASE: 'doxo'
    
    volumes:
      - mysql_data:/var/lib/mysql/data
    restart: always
  
volumes:
  mysql_data:
