-- CreateTable
CREATE TABLE "Produtos" (
    "id" SERIAL NOT NULL,
    "marca" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "unidade" TEXT NOT NULL DEFAULT 'UN',
    "ncm" TEXT NOT NULL,
    "valor_unitario" DOUBLE PRECISION NOT NULL,
    "ean" TEXT NOT NULL,
    "codigo" TEXT NOT NULL,
    "codigo_produto_integracao" TEXT NOT NULL,
    "peso_bruto" DOUBLE PRECISION NOT NULL,
    "ageToBuy" INTEGER NOT NULL,
    "qtd" DOUBLE PRECISION NOT NULL,
    "dias_garantia" INTEGER NOT NULL,
    "tagId" TEXT NOT NULL,
    "tagChecked" BOOLEAN NOT NULL,
    "datamatrixId" TEXT NOT NULL,
    "aliquota_cofins" DOUBLE PRECISION NOT NULL,
    "aliquota_ibpt" DOUBLE PRECISION NOT NULL,
    "aliquota_icms" DOUBLE PRECISION NOT NULL,
    "aliquota_pis" DOUBLE PRECISION NOT NULL,
    "cest" TEXT,
    "cfop" TEXT,
    "csosn_icms" TEXT,
    "cst_cofins" TEXT,
    "cst_icms" TEXT,
    "cst_pis" TEXT,
    "per_icms_fcp" DOUBLE PRECISION NOT NULL,
    "red_base_cofins" DOUBLE PRECISION NOT NULL,
    "red_base_icms" DOUBLE PRECISION NOT NULL,
    "red_base_pis" DOUBLE PRECISION NOT NULL,
    "tipoItem" TEXT NOT NULL,

    CONSTRAINT "Produtos_pkey" PRIMARY KEY ("id")
);
